# ARCHIVO GENERADO: datos de los 31 puntos de recoleccion oficiales.
# Se usan en el "seed" para llenar la tabla puntos_comunitarios la
# primera vez que arranca el backend. NO editar a mano.

PUNTOS_OFICIALES = [
    {
        "nombre": "Punto Av. Argentina",
        "latitud": -18.475579,
        "longitud": -70.304025,
        "sector": "Cuadrante 1",
        "dias_recoleccion": "Martes - Jueves - Domingo",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Orgánico",
    },
    {
        "nombre": "Punto Av. Capitán Ávalos",
        "latitud": -18.484204,
        "longitud": -70.304085,
        "sector": "Cuadrante 1",
        "dias_recoleccion": "Martes - Jueves - Domingo",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Plástico",
    },
    {
        "nombre": "Punto Av. Tucapel",
        "latitud": -18.473968,
        "longitud": -70.31172,
        "sector": "Cuadrante 1",
        "dias_recoleccion": "Martes - Jueves - Domingo",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Vidrio",
    },
    {
        "nombre": "Punto calle San Marcos",
        "latitud": -18.481999,
        "longitud": -70.301602,
        "sector": "Cuadrante 1",
        "dias_recoleccion": "Martes - Jueves - Domingo",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Papel/Cartón",
    },
    {
        "nombre": "Punto calle Colón",
        "latitud": -18.504692,
        "longitud": -70.303207,
        "sector": "Cuadrante 2",
        "dias_recoleccion": "Martes - Jueves - Domingo",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Metales",
    },
    {
        "nombre": "Punto Av. Diego Portales",
        "latitud": -18.487353,
        "longitud": -70.304374,
        "sector": "Cuadrante 2",
        "dias_recoleccion": "Martes - Jueves - Domingo",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Aluminio",
    },
    {
        "nombre": "Punto Av. General Velásquez",
        "latitud": -18.483043,
        "longitud": -70.312203,
        "sector": "Cuadrante 2",
        "dias_recoleccion": "Martes - Jueves - Domingo",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Orgánico",
    },
    {
        "nombre": "Punto calle Lynch",
        "latitud": -18.478926,
        "longitud": -70.297474,
        "sector": "Cuadrante 3",
        "dias_recoleccion": "Lunes - Miércoles - Viernes",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Plástico",
    },
    {
        "nombre": "Punto calle Patricio Lynch",
        "latitud": -18.490295,
        "longitud": -70.286248,
        "sector": "Cuadrante 3",
        "dias_recoleccion": "Lunes - Miércoles - Viernes",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Vidrio",
    },
    {
        "nombre": "Punto calle Maipú",
        "latitud": -18.4885,
        "longitud": -70.285443,
        "sector": "Cuadrante 3",
        "dias_recoleccion": "Lunes - Miércoles - Viernes",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Papel/Cartón",
    },
    {
        "nombre": "Punto sector Cabo Aroca",
        "latitud": -18.489611,
        "longitud": -70.289356,
        "sector": "Cuadrante 3",
        "dias_recoleccion": "Lunes - Miércoles - Viernes",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Metales",
    },
    {
        "nombre": "Punto pasaje Azapa",
        "latitud": -18.507073,
        "longitud": -70.305758,
        "sector": "Cuadrante 4",
        "dias_recoleccion": "Lunes - Miércoles - Viernes",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Aluminio",
    },
    {
        "nombre": "Punto Av. Las Torres",
        "latitud": -18.501081,
        "longitud": -70.309165,
        "sector": "Cuadrante 4",
        "dias_recoleccion": "Lunes - Miércoles - Viernes",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Orgánico",
    },
    {
        "nombre": "Punto Av. Luis Beretta",
        "latitud": -18.502473,
        "longitud": -70.308677,
        "sector": "Cuadrante 4",
        "dias_recoleccion": "Lunes - Miércoles - Viernes",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Plástico",
    },
    {
        "nombre": "Punto Av. Pedro Aguirre Cerda",
        "latitud": -18.501362,
        "longitud": -70.296379,
        "sector": "Cuadrante 4",
        "dias_recoleccion": "Lunes - Miércoles - Viernes",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Vidrio",
    },
    {
        "nombre": "Punto Av. Comandante San Martín",
        "latitud": -18.471426,
        "longitud": -70.306303,
        "sector": "Cuadrante 5",
        "dias_recoleccion": "Martes - Jueves - Domingo",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Papel/Cartón",
    },
    {
        "nombre": "Punto calle Yungay",
        "latitud": -18.472777,
        "longitud": -70.307696,
        "sector": "Cuadrante 5",
        "dias_recoleccion": "Martes - Jueves - Domingo",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Metales",
    },
    {
        "nombre": "Punto pasaje Juan Noe",
        "latitud": -18.466451,
        "longitud": -70.302552,
        "sector": "Cuadrante 5",
        "dias_recoleccion": "Martes - Jueves - Domingo",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Aluminio",
    },
    {
        "nombre": "Punto calle Sotomayor",
        "latitud": -18.469301,
        "longitud": -70.30899,
        "sector": "Cuadrante 5",
        "dias_recoleccion": "Martes - Jueves - Domingo",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Orgánico",
    },
    {
        "nombre": "Punto calle Prat",
        "latitud": -18.46794,
        "longitud": -70.299238,
        "sector": "Cuadrante 6",
        "dias_recoleccion": "Martes - Jueves - Domingo",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Plástico",
    },
    {
        "nombre": "Punto calle Rómulo Peña",
        "latitud": -18.472381,
        "longitud": -70.285277,
        "sector": "Cuadrante 6",
        "dias_recoleccion": "Martes - Jueves - Domingo",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Vidrio",
    },
    {
        "nombre": "Punto calle Baquedano",
        "latitud": -18.469072,
        "longitud": -70.292588,
        "sector": "Cuadrante 6",
        "dias_recoleccion": "Martes - Jueves - Domingo",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Papel/Cartón",
    },
    {
        "nombre": "Punto Villa El Solar",
        "latitud": -18.468505,
        "longitud": -70.287756,
        "sector": "Cuadrante 6",
        "dias_recoleccion": "Martes - Jueves - Domingo",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Metales",
    },
    {
        "nombre": "Punto Av. Chile",
        "latitud": -18.473782,
        "longitud": -70.288145,
        "sector": "Cuadrante 7",
        "dias_recoleccion": "Lunes - Miércoles - Viernes",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Aluminio",
    },
    {
        "nombre": "Punto pasaje Los Industriales",
        "latitud": -18.489329,
        "longitud": -70.287445,
        "sector": "Cuadrante 7",
        "dias_recoleccion": "Lunes - Miércoles - Viernes",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Orgánico",
    },
    {
        "nombre": "Punto Población Chinchorro",
        "latitud": -18.484404,
        "longitud": -70.288291,
        "sector": "Cuadrante 7",
        "dias_recoleccion": "Lunes - Miércoles - Viernes",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Plástico",
    },
    {
        "nombre": "Punto esquina 21 de Mayo",
        "latitud": -18.470293,
        "longitud": -70.282901,
        "sector": "Cuadrante 7",
        "dias_recoleccion": "Lunes - Miércoles - Viernes",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Vidrio",
    },
    {
        "nombre": "Punto Av. Santa María",
        "latitud": -18.480117,
        "longitud": -70.278546,
        "sector": "Cuadrante 8",
        "dias_recoleccion": "Lunes - Miércoles - Viernes",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Papel/Cartón",
    },
    {
        "nombre": "Punto calle O'Higgins",
        "latitud": -18.477729,
        "longitud": -70.275955,
        "sector": "Cuadrante 8",
        "dias_recoleccion": "Lunes - Miércoles - Viernes",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Metales",
    },
    {
        "nombre": "Punto Av. Argentina",
        "latitud": -18.475864,
        "longitud": -70.282451,
        "sector": "Cuadrante 8",
        "dias_recoleccion": "Lunes - Miércoles - Viernes",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Aluminio",
    },
    {
        "nombre": "Punto Av. Capitán Ávalos",
        "latitud": -18.482124,
        "longitud": -70.279486,
        "sector": "Cuadrante 8",
        "dias_recoleccion": "Lunes - Miércoles - Viernes",
        "horario": "Desde las 21:00 h.",
        "tipo_residuo": "Orgánico",
    },
]
